/*
 * This source file was generated by the Gradle 'init' task
 */
package test.java.org.example;

import org.junit.Test;
import static junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }   
}
